"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/auth";
import { getSupabase } from "@/lib/supabase";
import { SITE, STATUSES, LEADERS, feeFor, usd, ngn } from "@/lib/content";
import { Avatar, Spinner, StatusPill, Toast } from "@/components/ui";
import type { Payment, Profile } from "@/lib/types";

const NAV = [["overview", "Overview"], ["regs", "Registrations"], ["pending", "Pending approvals"], ["payments", "Payments"], ["unpaid", "Unpaid"], ["donations", "Donations"], ["attendance", "Attendance"], ["community", "Community"], ["committee", "Committee"], ["leaders", "Leaders"], ["settings", "Settings"]];

export default function Admin() {
  const { session, profile, loading } = useAuth(); const router = useRouter(); const sb = getSupabase();
  const [tab, setTab] = useState("overview"); const [people, setPeople] = useState<Profile[]>([]); const [pays, setPays] = useState<Payment[]>([]); const [att, setAtt] = useState<any[]>([]); const [msgCount, setMsgCount] = useState(0); const [plans, setPlans] = useState(0);
  const [q, setQ] = useState(""); const [fs, setFs] = useState(""); const [fp, setFp] = useState(""); const [amt, setAmt] = useState<Record<string, string>>({}); const [rsn, setRsn] = useState<Record<string, string>>({}); const [msg, setMsg] = useState<string | null>(null); const [ann, setAnn] = useState(""); const [resetSel, setResetSel] = useState<string[]>([]); const [resetConfirm, setResetConfirm] = useState(""); const [proofUrl, setProofUrl] = useState<string | null>(null);
  const toast = (m: string) => { setMsg(m); setTimeout(() => setMsg(null), 3000); };
  const isAdmin = profile?.role === "admin"; const canVerify = isAdmin || (profile?.role === "committee" && profile?.can_verify_payments);
  useEffect(() => { if (!loading && !session) router.replace("/login"); if (!loading && profile && profile.role === "participant") router.replace("/dashboard"); }, [loading, session, profile, router]);
  async function load() { if (!sb) return; const [a, b, c, d, e] = await Promise.all([sb.from("profiles").select("*").order("created_at", { ascending: false }), sb.from("payments").select("*, profiles:user_id(full_name,photo_url,status,sponsor_name,emerald_director)").order("created_at", { ascending: false }), sb.from("attendance").select("*"), sb.from("messages").select("id", { count: "exact", head: true }), sb.from("plans").select("user_id", { count: "exact", head: true })]);
    setPeople((a.data as Profile[]) ?? []); setPays((b.data as Payment[]) ?? []); setAtt(c.data ?? []); setMsgCount(d.count ?? 0); setPlans(e.count ?? 0); }
  useEffect(() => { if (profile && profile.role !== "participant") load(); }, [profile]); // eslint-disable-line
  if (loading || !session || !profile || profile.role === "participant") return <Spinner />;

  const parts = people.filter((p) => p.role === "participant");
  const state = (p: Profile) => { const f = feeFor(p.status); if (!f) return "Free"; const ps = pays.filter((x) => x.user_id === p.id && x.type === "registration"); return ps.some((x) => x.status === "approved") ? "Approved" : ps.some((x) => x.status === "pending") ? "Pending" : ps.some((x) => x.status === "rejected") ? "Rejected" : "Unpaid"; };
  const approvedUsd = (x: Payment) => (x.status === "approved" ? x.approved_amount_usd ?? 0 : 0);
  const raised = pays.reduce((a, x) => a + approvedUsd(x), 0); const fees = pays.filter((x) => x.type === "registration").reduce((a, x) => a + approvedUsd(x), 0);
  const pending = pays.filter((x) => x.status === "pending"); const confirmed = parts.filter((p) => ["Free", "Approved"].includes(state(p))).length;
  async function approve(p: Payment) { const v = Number(amt[p.id] ?? (p.currency === "NGN" ? Math.round(p.amount_claimed / SITE.rate) : p.amount_claimed)); if (!v) return toast("Enter the amount received"); const { error } = await sb!.from("payments").update({ status: "approved", approved_amount_usd: v, reviewed_by: session!.user.id, reviewed_at: new Date().toISOString() }).eq("id", p.id); if (error) return toast(error.message); if (p.type === "registration" && p.user_id) await sb!.from("profiles").update({ is_confirmed: true }).eq("id", p.user_id); await sb!.from("audit_log").insert({ actor_id: session!.user.id, action: "approve_payment", target_id: p.id, details: { usd: v } }); toast(`Approved ${usd(v)} — total funds raised updated`); load(); }
  async function reject(p: Payment) { const r = (rsn[p.id] ?? "").trim(); if (!r) return toast("Enter a rejection reason"); await sb!.from("payments").update({ status: "rejected", rejection_reason: r, reviewed_by: session!.user.id, reviewed_at: new Date().toISOString() }).eq("id", p.id); await sb!.from("audit_log").insert({ actor_id: session!.user.id, action: "reject_payment", target_id: p.id, details: { reason: r } }); toast("Rejected"); load(); }
  async function viewProof(path: string) { const { data } = await sb!.storage.from("proofs").createSignedUrl(path, 300); setProofUrl(data?.signedUrl ?? null); }
  async function setRole(id: string, role: string) { await sb!.from("profiles").update({ role }).eq("id", id); load(); }
  async function toggleVerify(p: Profile) { await sb!.from("profiles").update({ can_verify_payments: !p.can_verify_payments }).eq("id", p.id); load(); }
  async function mark(uid: string, day: number, on: boolean) { if (on) await sb!.from("attendance").delete().match({ user_id: uid, day }); else await sb!.from("attendance").insert({ user_id: uid, day, recorded_by: session!.user.id }); load(); }
  async function postAnn() { if (!ann.trim()) return; await sb!.from("announcements").insert({ body: ann.trim(), author_id: session!.user.id }); setAnn(""); toast("Announcement posted"); }
  async function doReset() { if (resetConfirm !== "RESET" || !resetSel.length) return; const { data, error } = await sb!.rpc("admin_reset", { targets: resetSel }); if (error) return toast(error.message); toast("Reset done: " + JSON.stringify(data)); setResetSel([]); setResetConfirm(""); load(); }
  const csv = () => { const rows = [["Name", "Email", "Phone", "Status", "Sponsor", "SM", "EM", "Director", "ED", "Payment", "Registered"], ...parts.map((p) => [p.full_name, p.email, p.phone, p.status, p.sponsor_name, p.senior_manager, p.executive_manager, p.director, p.emerald_director, state(p), p.created_at])]; const blob = new Blob([rows.map((r) => r.map((v) => `"${(v ?? "").toString().replace(/"/g, '""')}"`).join(",")).join("\n")], { type: "text/csv" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "registrations.csv"; a.click(); };
  const filtered = parts.filter((p) => (!q || p.full_name.toLowerCase().includes(q.toLowerCase()) || p.email.toLowerCase().includes(q.toLowerCase())) && (!fs || p.status === fs) && (!fp || state(p) === fp));
  const byStatus = STATUSES.map((s) => [s.key, parts.filter((p) => p.status === s.key).length] as const); const mx = Math.max(1, ...byStatus.map((x) => x[1]));
  const Tile = ({ l, v, sub, hi }: { l: string; v: string | number; sub?: string; hi?: boolean }) => <div className={`card ${hi ? "bg-azure text-white border-azure" : ""}`}><div className={`text-[11px] uppercase tracking-wider ${hi ? "opacity-80" : "text-muted"}`}>{l}</div><div className={`text-2xl font-extrabold mt-1 ${hi ? "text-amber" : "text-azure"}`}>{v}</div>{sub && <div className={`text-xs ${hi ? "opacity-80" : "text-muted"}`}>{sub}</div>}</div>;
  const RESETS = [["participants", "Participants & registrations (their payments, plans, messages and uploads too)"], ["payments", "Payments & donations (resets Total funds raised)"], ["attendance", "Attendance records"], ["plans", "Action plans, notes, to-dos and trackers"], ["messages", "Community chat messages"], ["dms", "Direct messages"], ["connections", "Connections and requests"], ["contact", "Contact form messages"], ["audit", "Activity feed and audit log"]];

  return (<section className="wrap py-6">
    <div className="rounded-xl bg-amber/15 border border-amber p-3 text-sm mb-4">Admin area · signed in as <b>{profile.email}</b> ({profile.role}).</div>
    <div className="grid md:grid-cols-[210px_1fr] gap-0 rounded-2xl overflow-hidden border border-line">
      <aside className="bg-azure text-white p-3 flex md:flex-col gap-1 overflow-x-auto">{NAV.map(([k, l]) => <button key={k} onClick={() => setTab(k)} className={`text-left rounded-lg px-3 py-2 text-sm font-semibold whitespace-nowrap flex justify-between ${tab === k ? "bg-white/15" : "opacity-85 hover:bg-white/10"}`}>{l}{k === "pending" && pending.length > 0 && <span className="rounded-full bg-amber text-ink px-2 text-xs">{pending.length}</span>}</button>)}</aside>
      <div className="bg-tint2 p-5 min-h-[600px]">
        {tab === "overview" && <>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Tile hi l="Total funds raised (approved)" v={usd(raised)} sub={`${ngn(raised * SITE.rate)} · fees ${usd(fees)} · donations ${usd(raised - fees)}`} /><Tile l="Total sign-ups" v={parts.length} /><Tile l="Confirmed" v={confirmed} sub="approved or free" /><Tile l="Pending approval" v={pending.length} /></div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mt-3"><Tile l="Unpaid" v={parts.filter((p) => ["Unpaid", "Rejected"].includes(state(p))).length} /><Tile l="Messages" v={msgCount} /><Tile l="Plans created" v={plans} /><Tile l="Attendance records" v={att.length} /></div>
          <div className="card mt-4"><h3 className="text-base">Sign-ups by status</h3><div className="flex items-end gap-2 h-32 mt-3">{byStatus.map(([k, v]) => <div key={k} className="flex-1 flex flex-col items-center gap-1"><span className="text-xs font-bold text-azure">{v}</span><div className="w-full rounded-t bg-sky" style={{ height: `${(v / mx) * 90}%`, minHeight: 3 }} /><span className="text-[9px] text-muted truncate w-full text-center">{k.replace("Executive", "Exec").replace("Senior", "Sr").replace("Emerald", "Em.")}</span></div>)}</div></div>
          <div className="card mt-4"><h3 className="text-base">Recent activity</h3>{pays.slice(0, 6).map((p) => <div key={p.id} className="flex justify-between text-sm py-2 border-t border-line"><span><b>{p.profiles?.full_name ?? "Guest"}</b> · {p.type} {p.status} · {p.method}</span><span className="text-muted">{new Date(p.created_at).toLocaleDateString()}</span></div>)}</div></>}

        {tab === "regs" && <><div className="flex flex-wrap gap-2 mb-3"><input className="input !w-56" placeholder="Search name or email" value={q} onChange={(e) => setQ(e.target.value)} /><select className="input !w-44" value={fs} onChange={(e) => setFs(e.target.value)}><option value="">All statuses</option>{STATUSES.map((s) => <option key={s.key}>{s.key}</option>)}</select><select className="input !w-44" value={fp} onChange={(e) => setFp(e.target.value)}><option value="">All payment states</option>{["Free", "Unpaid", "Pending", "Approved", "Rejected"].map((s) => <option key={s}>{s}</option>)}</select><button onClick={csv} className="btn btn-outline !py-1.5 !text-xs">Export CSV</button></div>
          <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Name</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Sponsor</th><th className="px-3 py-2">SM</th><th className="px-3 py-2">EM</th><th className="px-3 py-2">ED</th><th className="px-3 py-2">Fee</th><th className="px-3 py-2">Payment</th><th className="px-3 py-2">Registered</th>{isAdmin && <th className="px-3 py-2"></th>}</tr></thead>
            <tbody>{filtered.map((p) => <tr key={p.id} className="border-t border-line"><td className="px-3 py-2"><div className="flex items-center gap-2"><Avatar name={p.full_name} url={p.photo_url} size={32} /><div><b>{p.full_name}</b><div className="text-xs text-muted">{p.email} · {p.phone}</div></div></div></td><td className="px-3 py-2">{p.status}</td><td className="px-3 py-2">{p.sponsor_name ?? "—"}</td><td className="px-3 py-2">{p.senior_manager ?? "—"}</td><td className="px-3 py-2">{p.executive_manager ?? "—"}</td><td className="px-3 py-2">{p.emerald_director ?? "—"}</td><td className="px-3 py-2">{feeFor(p.status) ? usd(feeFor(p.status)) : "Free"}</td><td className="px-3 py-2"><StatusPill s={state(p)} /></td><td className="px-3 py-2 text-xs text-muted">{new Date(p.created_at).toLocaleDateString()}</td>{isAdmin && <td className="px-3 py-2"><button onClick={() => setRole(p.id, "committee")} className="text-xs font-bold text-azure">Make committee</button></td>}</tr>)}</tbody></table>{!filtered.length && <p className="p-4 text-sm text-muted">No registrations match.</p>}</div></>}

        {tab === "pending" && (pending.length ? pending.map((p) => <div key={p.id} className="card mb-3 grid md:grid-cols-[1fr_auto] gap-4"><div><div className="flex items-center gap-3"><Avatar name={p.profiles?.full_name} url={p.profiles?.photo_url} size={44} /><div><b>{p.profiles?.full_name ?? "Guest donor"}</b> <span className="pill bg-amber text-ink">{p.profiles?.status ?? p.type}</span><div className="text-xs text-muted">Sponsor: {p.profiles?.sponsor_name ?? "—"} · ED: {p.profiles?.emerald_director ?? "—"}</div></div></div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mt-3 text-sm"><div><div className="text-xs text-muted">Type</div><b>{p.type}</b></div><div><div className="text-xs text-muted">Method</div><b>{p.method}</b></div><div><div className="text-xs text-muted">Claimed</div><b>{p.currency === "NGN" ? ngn(p.amount_claimed) : usd(p.amount_claimed)}</b></div><div><div className="text-xs text-muted">Due</div><b>{p.type === "donation" ? "—" : `${usd(p.amount_due_usd)} / ${ngn(p.amount_due_usd * SITE.rate)}`}</b></div><div><div className="text-xs text-muted">Reference</div><b>{p.reference ?? "—"}</b></div><div><div className="text-xs text-muted">Date</div><b>{new Date(p.created_at).toLocaleString()}</b></div></div>
            {canVerify && <><div className="grid sm:grid-cols-2 gap-2 mt-3"><div><label className="label">Confirm amount received (USD)</label><input className="input" value={amt[p.id] ?? (p.currency === "NGN" ? Math.round(p.amount_claimed / SITE.rate) : p.amount_claimed)} onChange={(e) => setAmt({ ...amt, [p.id]: e.target.value })} /></div><div><label className="label">Rejection reason (if rejecting)</label><input className="input" placeholder="e.g. Screenshot unclear" value={rsn[p.id] ?? ""} onChange={(e) => setRsn({ ...rsn, [p.id]: e.target.value })} /></div></div>
            <div className="flex gap-2 mt-3"><button onClick={() => approve(p)} className="btn btn-primary !py-1.5 !text-xs">Approve</button><button onClick={() => reject(p)} className="btn btn-outline !py-1.5 !text-xs">Reject</button></div></>}</div>
          <div>{p.proof_url ? <button onClick={() => viewProof(p.proof_url!)} className="btn btn-outline !py-1.5 !text-xs">View proof</button> : <span className="text-xs text-muted">No proof uploaded</span>}</div></div>) : <div className="card bg-green-50 border-green-200 text-sm text-green-900">No pending approvals — you&apos;re all caught up.</div>)}

        {(tab === "payments" || tab === "donations") && <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Name</th><th className="px-3 py-2">Type</th><th className="px-3 py-2">Method</th><th className="px-3 py-2">Claimed</th><th className="px-3 py-2">Approved</th><th className="px-3 py-2">Status</th></tr></thead>
          <tbody>{pays.filter((p) => tab === "payments" || p.type === "donation").map((p) => <tr key={p.id} className="border-t border-line"><td className="px-3 py-2 text-xs">{new Date(p.created_at).toLocaleDateString()}</td><td className="px-3 py-2">{p.profiles?.full_name ?? "Guest"}</td><td className="px-3 py-2">{p.type}</td><td className="px-3 py-2">{p.method}</td><td className="px-3 py-2">{p.currency === "NGN" ? ngn(p.amount_claimed) : usd(p.amount_claimed)}</td><td className="px-3 py-2">{p.status === "approved" ? usd(p.approved_amount_usd ?? 0) : "—"}</td><td className="px-3 py-2"><StatusPill s={p.status} />{p.rejection_reason && <div className="text-xs text-muted">{p.rejection_reason}</div>}</td></tr>)}</tbody></table></div>}

        {tab === "unpaid" && <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Name</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Fee due</th><th className="px-3 py-2">State</th><th className="px-3 py-2">Phone</th><th className="px-3 py-2"></th></tr></thead>
          <tbody>{parts.filter((p) => ["Unpaid", "Pending", "Rejected"].includes(state(p))).map((p) => <tr key={p.id} className="border-t border-line"><td className="px-3 py-2 font-bold">{p.full_name}</td><td className="px-3 py-2">{p.status}</td><td className="px-3 py-2">{usd(feeFor(p.status))}</td><td className="px-3 py-2"><StatusPill s={state(p)} /></td><td className="px-3 py-2">{p.phone}</td><td className="px-3 py-2"><a className="btn btn-outline !py-1 !text-xs" target="_blank" rel="noopener" href={`https://wa.me/${(p.phone ?? "").replace(/\D/g, "")}?text=${encodeURIComponent(`Hi ${p.full_name}, this is the Magnificent 5 Days Bootcamp team. Your registration fee of ${usd(feeFor(p.status))} is still pending. Pay and upload your proof at ${location.origin}/register`)}`}>WhatsApp reminder</a></td></tr>)}</tbody></table></div>}

        {tab === "attendance" && <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Participant</th>{[1, 2, 3, 4, 5].map((d) => <th key={d} className="px-3 py-2 text-center">Day {d}</th>)}<th className="px-3 py-2">Total</th></tr></thead>
          <tbody>{parts.map((p) => { const days = att.filter((a) => a.user_id === p.id).map((a) => a.day); return <tr key={p.id} className="border-t border-line"><td className="px-3 py-2 font-bold">{p.full_name}<div className="text-xs text-muted font-normal">{p.status}</div></td>{[1, 2, 3, 4, 5].map((d) => <td key={d} className="px-3 py-2 text-center"><input type="checkbox" checked={days.includes(d)} onChange={() => mark(p.id, d, days.includes(d))} /></td>)}<td className="px-3 py-2 font-bold">{days.length}/5</td></tr>; })}</tbody></table></div>}

        {tab === "community" && <div className="grid gap-4 md:grid-cols-2"><div className="card"><h3 className="text-base">Post an announcement</h3><p className="text-xs text-muted">Pinned at the top of every chat room.</p><textarea className="input mt-2 min-h-[90px]" value={ann} onChange={(e) => setAnn(e.target.value)} /><button onClick={postAnn} className="btn btn-primary mt-2 !py-1.5 !text-xs">Post</button></div><div className="card"><h3 className="text-base">Stats</h3><p className="text-sm mt-2">Messages: <b>{msgCount}</b></p><p className="text-sm">Plans created: <b>{plans}</b></p><p className="text-sm">Members: <b>{parts.length}</b></p></div></div>}

        {tab === "committee" && <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Name</th><th className="px-3 py-2">Role</th><th className="px-3 py-2">Can verify payments</th><th className="px-3 py-2"></th></tr></thead>
          <tbody>{people.filter((p) => p.role !== "participant").map((p) => <tr key={p.id} className="border-t border-line"><td className="px-3 py-2 font-bold">{p.full_name}<div className="text-xs text-muted font-normal">{p.email}</div></td><td className="px-3 py-2">{p.role}</td><td className="px-3 py-2">{p.role === "admin" ? "Always" : p.can_verify_payments ? "Yes" : "No"}</td><td className="px-3 py-2 flex gap-2">{isAdmin && p.role === "committee" && <><button onClick={() => toggleVerify(p)} className="btn btn-outline !py-1 !text-xs">{p.can_verify_payments ? "Turn off verifying" : "Allow verifying"}</button><button onClick={() => setRole(p.id, "participant")} className="text-xs text-red-700 font-bold">Remove</button></>}</td></tr>)}</tbody></table><p className="p-3 text-xs text-muted">Promote someone from the Registrations tab with &quot;Make committee&quot;. Admins are set from Settings → Admins.</p></div>}

        {tab === "leaders" && <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-tint text-left text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-3 py-2">Name</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{LEADERS.map((l) => <tr key={l.name} className="border-t border-line"><td className="px-3 py-2 font-bold">{l.name}</td><td className="px-3 py-2">{l.status}</td></tr>)}</tbody></table><p className="p-3 text-xs text-muted">These names fill the drop-downs in the sign-up form. Edit them in lib/content.ts.</p></div>}

        {tab === "settings" && <div className="grid gap-4 md:grid-cols-2">
          <div className="card"><h3 className="text-base">Fees &amp; rate</h3><p className="text-xs text-muted">Naira rate: ₦{SITE.rate.toLocaleString()} per $1</p>{STATUSES.map((s) => <div key={s.key} className="flex justify-between text-sm py-1.5 border-t border-line"><span>{s.key}</span><b>{s.fee ? usd(s.fee) : "Free"}</b></div>)}</div>
          <div className="card"><h3 className="text-base">Payment details</h3><div className="text-sm space-y-1 mt-2"><p>Cleva / Grey / Raenest tag: <b>@saliukehinde</b> (Kehinde Saliu)</p><p>Naira: <b>Palmpay · 9066208990 · Saliu Kehinde</b></p><p>WhatsApp group: <a className="text-azure" href={SITE.whatsappGroup} target="_blank" rel="noopener">link</a></p><p>Admin email: <b>{profile.email}</b></p></div></div>
          {isAdmin && <div className="card md:col-span-2"><h3 className="text-base">Admins</h3><p className="text-xs text-muted">Make any registered user an admin.</p><div className="flex flex-wrap gap-2 mt-2">{people.filter((p) => p.role !== "admin").slice(0, 50).map((p) => <button key={p.id} onClick={() => setRole(p.id, "admin")} className="rounded-full border border-line px-3 py-1 text-xs font-semibold hover:border-sky">{p.full_name}</button>)}</div></div>}
          {isAdmin && <div className="card md:col-span-2 border-red-200"><h3 className="text-base text-red-700">Reset data</h3><p className="text-xs text-muted">Choose exactly what to clear. Admin and committee accounts, settings and content are always kept.</p>
            <div className="grid sm:grid-cols-2 gap-1 mt-3">{RESETS.map(([k, l]) => <label key={k} className="flex gap-2 text-sm"><input type="checkbox" checked={resetSel.includes(k)} onChange={(e) => setResetSel(e.target.checked ? [...resetSel, k] : resetSel.filter((x) => x !== k))} />{l}</label>)}</div>
            <div className="flex gap-2 mt-2 text-xs"><button className="text-azure font-bold" onClick={() => setResetSel(RESETS.map((r) => r[0]))}>Select all</button><button className="text-muted font-bold" onClick={() => setResetSel([])}>Clear</button></div>
            <div className="flex flex-wrap gap-2 mt-3 items-center"><input className="input !w-40" placeholder="Type RESET" value={resetConfirm} onChange={(e) => setResetConfirm(e.target.value)} /><button disabled={resetConfirm !== "RESET" || !resetSel.length} onClick={doReset} className="btn bg-red-600 text-white disabled:opacity-40">Reset selected</button></div></div>}
        </div>}
      </div>
    </div>
    {proofUrl && <div className="fixed inset-0 z-50 bg-black/70 grid place-items-center p-6" onClick={() => setProofUrl(null)}><div className="bg-white rounded-2xl p-3 max-w-3xl max-h-[90vh] overflow-auto"><img src={proofUrl} alt="Proof" className="max-h-[80vh]" /><a href={proofUrl} target="_blank" rel="noopener" className="btn btn-outline mt-2 !py-1.5 !text-xs">Open in new tab</a></div></div>}
    <Toast msg={msg} />
  </section>);
}
